### ISSUE TITLE
Access to fetch at 'https://www.athmovil.com/rs/v2/transactionStatus' from origin 'http://localhost:8080' has been blocked by CORS policy:

### ISSUE THREAD

**Issue by Cyberfolks** [evertec/athmovil-javascript-api#7]

**Comment by Cyberfolks** [comment]
Access to fetch at 'https://www.athmovil.com/rs/v2/transactionStatus' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by lfontanez** [comment]
Puedes intentar con JSONP
https://www.w3schools.com/js/js_json_jsonp.asp
